### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by drcrook1** [Azure/azure-data-lake-store-python#133]
Hello,

It seems that no matter what I do, I can not get access to my store.  Below is the exact code I am using (minus the password etc.)

The user is the subscription global admin and as such is an owner over the resource.  I have also tried the service account I created with office 365 and have verified the user is a contributor to the resource group owning data lake as well as ensuring has read, write, execute access from the root folder in data lake.

This is customer blocking, any tips are welcome.

```
#%% imports
## Use this only for Azure AD service-to-service authentication
from azure.common.credentials import ServicePrincipalCredentials
## Use this only for Azure AD end-user authentication
from azure.common.credentials import UserPassCredentials
## Use this only for Azure AD multi-factor authentication
from msrestazure.azure_active_directory import AADTokenCredentials
## Required for Azure Data Lake Store account management
from azure.mgmt.datalake.store import DataLakeStoreAccountManagementClient
from azure.mgmt.datalake.store.models import DataLakeStoreAccount
## Required for Azure Data Lake Store filesystem management
from azure.datalake.store import core, lib, multithread
# Common Azure imports
from azure.mgmt.resource.resources import ResourceManagementClient
from azure.mgmt.resource.resources.models import ResourceGroup
## Use these as needed for your application
import logging, getpass, pprint, uuid, time

subscriptionId = 'YOUR ID'
adlsAccountName = 'YOUR NAME'
#Best to use Office 365 or similiar and provision a non licensed user
#who can be your batch management user
user = 'user@domain.com'
password = 'YOUR PASS'

token = lib.auth(tenant_id = "common", username = user, password = password)
credentials = UserPassCredentials(user, password)

#%%
adlsAccountClient = DataLakeStoreAccountManagementClient(credentials, subscriptionId)
adlsFileSystemClient = core.AzureDLFileSystem(token, store_name=adlsAccountName)

#%%
adlsFileSystemClient.ls('', detail=True)
```

------------------------
ERROR
-----------------------
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-31-7050d508e59f> in <module>()
      1 #%%
----> 2 adlsFileSystemClient.ls('', detail=True)

C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\azure\datalake\store\core.py in ls(self, path, detail)
    117         """ List single directory with or without details """
    118         path = AzureDLPath(path)
--> 119         files = self._ls(path)
    120         if not files:
    121             inf = self.info(path)

C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\azure\datalake\store\core.py in _ls(self, path)
    108         key = path.as_posix()
    109         if path not in self.dirs:
--> 110             out = self.azure.call('LISTSTATUS', path.as_posix())
    111             self.dirs[key] = out['FileStatuses']['FileStatus']
    112             for f in self.dirs[key]:

C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\azure\datalake\store\lib.py in call(self, op, path, **kwargs)
    303 
    304         if r.status_code == 403:
--> 305             self.log_response_and_raise(r, PermissionError(path))
    306         elif r.status_code == 404:
    307             self.log_response_and_raise(r, FileNotFoundError(path))

C:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\azure\datalake\store\lib.py in log_response_and_raise(self, response, exception, level)
    256                 msg += "\n(Response body was truncated)"
    257         logger.log(level, msg)
--> 258         raise exception
    259 
    260     def _is_json_response(self, response):

PermissionError: .

**Comment by drcrook1** [comment]
Decided to try the following code and got the following error instead:

`r = list(adlsAccountClient.account.list())
for items in r:
    print(items)`

**CloudError: Azure Error: InvalidAuthenticationTokenTenant
Message: The access token is from the wrong issuer 'https://sts.windows.net/e2b63ba7-49a3-486c-8b0d-bb4a6c408826/'. It must match the tenant 'https://sts.windows.net/7e6ce8cc-36a5-40de-98a7-1cfb8d3c9c95/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/7e6ce8cc-36a5-40de-98a7-1cfb8d3c9c95' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later**

**Comment by drcrook1** [comment]
Seeing this; https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-create-service-principal-portal but it is not an application attempting to do anything, its a user.  Lets say I did create an app, my app is just some random code running as a service somewhere and not actually an 'app'.

**Comment by begoldsm** [comment]
@drcrook1 the issue you are seeing is indicative of a cross tenant authentication problem. Basically, the user you are authenticating with is targetting AAD tenant A, but the resource (ADL account) you want to access exists under AAD tenant B. This is not supported (as evidenced by the invalid token tenant message). 

This is an issue in two scenarios:
1. The user you are authenticating with only exists under AAD tenant A.
2. The user you are authenticating with has an entry in both AAD tenant A and AAD tenant B, but is defaulting to tenant A when targeting the 'common' tenant.

For the first scenario, you must add an entry for the user into AAD tenant B

For both the first and second scenario, you must initiate your authentication by targetting the specific tenant ID of the tenant that contains the ADL resource, instead of using the common tenant:

token = lib.auth(tenant_id = '**Tenant ID of AAD tenant with ADL resource**', username = user, password = password)
credentials = UserPassCredentials(user, password, **tenant='tenant ID of AAD tenant with ADL resource'**)

I agree that it is confusing that in one case you get a generic "permission error" and the other you get a more robust exception. I will work on getting the messaging consistent across these clients, since the underlying error should be the same.

**Comment by begoldsm** [comment]
@drcrook1 in addition to the post above I have some more specific information for you in order to enable your scenario:
1. All guest users (users being invited into a new AAD tenant) **must** be email enabled, as they are required to accept the invite. The invite operation does not complete until they approve the request.
2. In your specific case, and for others with an OrgID and LiveID account with the same name, it is highly recommended to follow the steps in the login prompt to merge/rename the accounts, which will help resolve automated authentication issues in the future. For reference, here is the link to help with that:
https://support.microsoft.com/en-us/help/11545/microsoft-account-rename-your-personal-account

To avoid this type of scenario, it is a good idea to keep all of your resources and users under the same tenant. While I know this is not always possible, it does help avoid this type of scenario, and also gives you better control over the user accounts, their permissions and their access to various resources.

With this information I am going to close out this issue. Please let me know if, even after following these steps, you still have issues connecting to and working with ADL.
