### ISSUE TITLE
slow performance downloading folders

### ISSUE THREAD

**Issue by drcrook1** [Azure/azure-data-lake-store-python#163]
I have probably 300,000 or so images from 40kb to 150kb each currently stored in ADLS I am attempting to download into a container.

The ADLS store is in Central US, the container is in East US.  We let the download job run overnight (14 hours or so) and the result is still nothing is downloaded.

Details on container: It is a Jupyter Notebook docker container running python 2.7.  It is mounted onto Azure Files and the drop location is Azure Files.

**Comment by begoldsm** [comment]
@drcrook1 you are going to get sub par performance in this situation due to latency issues between all of these different services. That being said, what is the actual command you are running to do the download and how many threads are you using, I would recommend somewhere between 16 - 32 threads.

And the usual question: what version of the client are you using.

**Comment by milanchandna** [comment]
@drcrook1, As begoldsm mentioned the performance is going to take a hit between all different services and in cross geo scenario. But I am worried about "nothing is downloaded" part. Please try with mentioned recommendations and see if you are still facing the similar issues.

As this thread was dead for almost an year, closing this issue, but you can happily reopen it again if you are still facing it.

In case you do, please answer the questions asked by begoldsm and post debug logs so that we can take a deeper look at the issue.
