### ISSUE TITLE
Enable Data Lake Store progress controller callback

### ISSUE THREAD

**Issue by clehene** [Azure/azure-data-lake-store-python#174]
### Description
This should report progress on transferred chunks (similar to blob store transfer)
```
Alive[#########################                                       ]  40.0881%
Finished[#############################################################]  100.0000%
```

**Comment by begoldsm** [comment]
@clehene  This is a an extension of enhancement: #142 for the CLI.

Currently progress support will show up if --verbose is specified in the CLI or verbose=True is passed in to the SDK directly, however it drastically reduces overall performance for folder upload/download when there are a large number of files, due to the single threaded nature of Python and the constant context switching between the callbacks and the actual upload/download.

That being said this is something the team is aware of and is part of the current planning discussion for the upcoming milestone. @matt1883 will be able to share more details once we have them.

**Comment by begoldsm** [comment]
Just saw that you also submitted a PR @clehene, thank you! The PR is: #175

**Comment by clehene** [comment]
@begoldsm it looks like the `progress`, `status` functions are pretty heavy as they will iterate across all files / chunks with every operation. The implementation in the PR makes use of the core progress controller and only updates transferred bytes, so IMHO shouldn't affect performance dramatically. Is there a benchmark test implemented so we could compare?

**Comment by begoldsm** [comment]
@clehene that is great to know! We do have a benchmark test although, unfortunately, it is not entirely self contained, as it assumes the existence of certain files with specific names. it exists in samples/benchmarks.py, and could easily be updated, I think, to create the files that it uses to test on execution instead of relying on them to be pre-existing. If you are up for making some additional improvements I won't stop you! 😄

**Comment by begoldsm** [comment]
#175 enables this.
