### ISSUE TITLE
Renaming and moving files not working

### ISSUE THREAD

**Issue by npezolano** [Azure/azure-data-lake-store-python#204]
Both AzureDLFileSystem.mv and AzureDLFileSystem.rename throw the following error on linux:

`DatalakeRESTException: Operation failed: RENAME, myfile.csv`

**Comment by milanchandna** [comment]
@npezolano Hi, Can you please share more details here so that it will help us debug the issue.
For example: 
1. Bit more of your code snippet.
2. Whether detailed "ls" and "create" command in parent directories(both source and destinantion) is working?
3. Detailed logs for rename and mv errors. Debug logs are preferred.
4. Is this problem particularly in one account?
5. Is this problem particularly in one directory?
6. Is this intermittent issue or regular one?
7. Can you share your account name and time and date of occurence of errors? This is just to check the logs from server side. You can personally mail me the details if you are not comfortable in sharing it here.

-Milan.

**Comment by npezolano** [comment]
Thanks and apologies this was an error on my end.
