### ISSUE TITLE
When downloading a directory that actually only has one file buried in it, the directory structure is not maintained

### ISSUE THREAD

**Issue by masangster** [Azure/azure-data-lake-store-python#214]
### Description
Using the ADLDownloader, when trying to download a directory with multiple subdirectories, if any of the lowest level folders have more than one file in them, the whole directory tree is downloaded as expected. However, if only one file actually exists in one of the lowest level subfolders, then the file is downloaded on its own as though it was only a single file specified for download, and not the whole directory. 

This is problematic when trying to programmatically interface with the ADL, pull down files to a VM, use them for computations, and then re-upload them when finished, as the expected file structure is not there for referencing file paths etc.

---

### Reproduction Steps
1. Connect to Azure Data lake Store using service to service application.
2. Download a subset of the ADL directory structure which may have many nested levels of subfolders, but only one of the lowest level subfolders actually has a file in it. Do this using eg. 
ADLDownloader(adlsFileSystemClient, rpath='RootFolder/Subfolder/Subfolder2', lpath='/localfolder', chunksize=1000000, buffersize=1000000, blocksize=1000000, client=None, run=True, overwrite=True, verbose=True)

Result: Only the single file is downloaded, it doesn't come within the subset of the file directory requested.. 

### Environment summary

**SDK Version:** What version of the SDK  are you using? (pip show azure-datalake-store)
0.0.19

**Python Version:** What Python version are you using? Is it 64-bit or 32-bit?  
3.6.2 64 bit

**OS Version:** What OS and version are you using?  
Windows 7 Enterprise 64 bit

**Shell Type:** What shell are you using? (e.g. bash, cmd.exe, Bash on Windows)  
Python with VS Code

**Comment by masangster** [comment]
Any progress on investigating this MS? As a large enterprise customer it is critical download behaviour is predictable and this currently prevents us from moving forward with the roll out of data lake as a storage solution.

**Comment by masangster** [comment]
Hi guys, any update on this?

**Comment by akharit** [comment]
This occurs due to https://github.com/Azure/azure-data-lake-store-python/blob/f50819ac1a256cf405e5cab9a2658a1427115714/azure/datalake/store/multithread.py#L197

The code for len(rfiles) == 1 does not do a check if only the file was requested explicitly or if the directory structure just happened to have a single file.

I am working on a fix, and AFAIK right now, it should be trivial. I am mainly checking if some other code is impacted by the fix, and working on a test case.

Branch url: https://github.com/Azure/azure-data-lake-store-python/tree/akharit-fixDirectoryStructureMaintain

@masangster In the other PR you mentioned about files not reliably downloading. Is that an issue as well? Apart from directory structure not being maintained, is the file possibly corrupted? If so, can you share more information on that?

**Comment by masangster** [comment]
Hi @akharit, in my testing if I am downloading a directory from rpath = /TestFolder/TestSubfolder, and TestSubFolder has multiple levels of directory underneath it, but only one file in one of the subdirectories, then the result (if I am downloading the directory to lpath = ./TestLocation/TestSubLocation) is that I end up with a folder at ./TestLocation as expected, and inside this I have one file named TestSubLocation, which has an unknown extension and size 1kB. So basically, the lpath is not used correctly, none of the structure under rpath is retained in the local version downloaded, and I also don't get a working version of the single file that was somewhere in the rpath directory tree.

**Comment by akharit** [comment]
@masangster Thanks! I did see that behavior i.e file created with unknown extension. It was basically the sdk trying to create a directory as a file. The current fix I have in branch is working for downloading single files with the directory tree for them, but it is not downloading directories that are empty. 

For example,
Assuming directory tree is 

```
a
└───b
    └─── c
    └─── d
         │e.txt
```
where a,b,c,d are directories and e.txt is a file under directory d.

If I try to download a to a local directory called a, it will create(using my branch) 
```
a
└───b
    └─── d
         │e.txt
```
on my system, and not create empty directory c.

I am still looking into this. From my observation, it actually never downloads an empty directory, whether the directory structure has a single file or multiple. I'll see if I need to create a separate issue for that if the fix is more involved, or fix it under this issue.

**Comment by masangster** [comment]
@akharit, thanks for this - I also agree that the empty directories not being downloaded isn’t ideal, so if this could be fixed as well it would be much appreciated. Happy to test if needed...

**Comment by akharit** [comment]
@masangster I have pushed a new release with the fix. Can you reply back if you are still facing this particular issue or something similar? 

Otherwise, I'll close this in around a week.

**Comment by masangster** [comment]
@akharit The directory now downloads as expected, however if there is already a directory in place that I want to overwrite, and "Overwrite=True" is specified in the call, it now throws an error at line 252 of multithread.py, described as: name 'errno' is not defined.

**Comment by akharit** [comment]
Not sure how this got missed. Possibly something I forgot to add to a change while doing a git commit. 

Just requires  an "import errno" at line 23 in multithread.py. Will fix ASAP.

**Comment by akharit** [comment]
@masangster This should be fixed. Are there any other issues? Otherwise, I'll close this.

**Comment by masangster** [comment]
@akharit this seems to be working as expected now. Thanks for your efforts! Can be closed.
