### ISSUE TITLE
In glob() details parameter is reverted

### ISSUE THREAD

**Issue by okhoma** [Azure/azure-data-lake-store-python#218]
### Description

There seems to be a typo in glob() function:

```
def glob(self, path, details=False, invalidate_cache=True):
        ...
        return [f for f in allfiles if AzureDLPath(f['name'] if details else f).match(path_as_posix)]
```

Note that it says `f['name'] if details else f`. 
It should, probably, be `f if details else f['name']`

**Comment by milanchandna** [comment]
f['name'] if details else f
here f is fetched from walk() which returns file detailed object if details is True else just the name.
In above line, we just have to pass the name of file in constructor of AzureDLPath.
So if details is True, name is fetched from f object,
which is why: f['name'] if details
else f is name anyways, which is why: else f

Hope that explains :)
